#! /usr/bin/env bash
echo "== Delete S3 Bucket =="

#Check if bucket name is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <bucket-name>"
    exit 1
fi

BUCKET_NAME=$1
#https://docs.aws.amazon.com/cli/latest/reference/s3api/delete-bucket.html
aws s3api delete-bucket \
--bucket "$BUCKET_NAME"