#! /usr/bin/env bash
set -e

echo "== Get newest S3 Bucket =="

#https://docs.aws.amazon.com/cli/latest/reference/s3api/list-buckets.html
aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0] | .Name'