#! /usr/bin/env bash
echo "== List S3 Objects =="
#Check if bucket name is provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <bucket-name>"
    exit 1
fi

BUCKET_NAME=$1

#https://docs.aws.amazon.com/cli/latest/reference/s3api/list-objects-v2.html
aws s3api list-objects-v2 \
--bucket "$BUCKET_NAME"